*** Variables ***
${data_001}       {"bannerDisplay":"slider"}    # update banner display to slider
${data_002}       {"bannerDisplay":"grid"}    # update banner display to grid
${data_003}       {"category":{"layoutProduct":2}}    #update product list to display 2 columns
${data_004}       {"category":{"layoutProduct":3}}    #update product list to display 3 columns
${data_005}       {"category":{"layoutProduct":4}}    #update product list to display 4 columns
${data_006}       {"category":{"layoutProduct":5}}    #update product list to display 5 columns
${data_007}       {"category":{"layoutProduct":6}}    #update product list to display 6 columns
${data_008}       {"category":{"autoLoad":0}}    #update product list to manual load TC027
${data_009}       {"category":{"autoLoad":1}}    #update product list to autoload TC028
${data_010}       {"category":{"visibleSidebar":1}}    #update product list to have sidebar
${data_011}       {"category":{"visibleSidebar":2}}    #update product list to have no sidebar
${data_012}       {"productDetail":{"displayWareHouse":1}}    #update product detail to display Warhouse
${data_013}       {"productDetail":{"displayWareHouse":0}}    #update product detail to not display Warhouse
${data_014}       {"productDetail":{"displayDescription":1}}    #update product detail to display Description
${data_015}       {"productDetail":{"displayDescription":0}}    #update product detail to not display Description
${data_016}       {"productDetail":{"displayComment":1}}    #update product detail to display Comment
${data_017}       {"productDetail":{"displayComment":0}}    #update product detail to not display Comment
${data_018}       {"productDetail":{"displayProductRelate":1}}    #update product detail to display Related Product
${data_019}       {"productDetail":{"displayProductRelate":0}}    #update product detail to not display Related Product
${data_reset}     {"theme":{"color":"#45A6AF","second_color":"#2C334D","backgroundColor":"#F9F9F9","backgroundColorHeader":"#fff","mainMenuBackgroundColor":"#0090da","font":"'Roboto', sans-serif","headerBackgroundMode":"light-mode","mainMenuBackgroundMode":"dark-mode"},"menu":{"main_menu":1,"sub_menu":1},"layoutProduct":6,"widthBanner":"full","bannerDisplay":"slider","profile":{"logo":"https://www.mykiot.vn/assets/images/kiotvietLogo.jpg"},"category":{"layoutProduct":5,"autoLoad":1,"visibleSidebar":1},"defaultCategory":{"isShow":true,"displayType":"list"},"productDetail":{"displayDescription":1,"displayComment":1,"displayProductRelate":1,"displayWareHouse":1},"priceBook":{"regularPrice":-1},"branch":{"branchInventory":[9113],"branchOrder":9113},"listBranches":[{"id":9113,"branchName":"Chi nhánh trung tâm","address":"just for test mykiot","locationName":"Hà Nội - Quận Hoàn Kiếm","retailerId":737280,"modifiedDate":"2020-07-30T13:31:45.6530000","createdDate":"2020-07-30T10:35:02.3500000"}],"customLayouts":[{"title":"Sản phẩm nổi bật","numberItem":4,"productIds":[11021617,11021609]},{"title":"Sản phẩm mới","numberItem":4,"productIds":[11021230,11021397,11021457,11021537]}],"syncCategoryCompleted":true,"settingKV":{"ManagerCustomerByBranch":false,"AllowOrderWhenOutStock":false,"AllowSellWhenOrderOutStock":true,"SellAllowOrder":true},"isReady":false,"lastModifiedFromNodeSync":"2020-07-30T03:35:38.000000Z","banner":[{"index":0,"alt":null,"link":null,"url":"https://admin.mykiot.vn/assets/images/StoreFrontBanner/Supermarket.jpg"}],"accessToken":{"isInternalApi":true,"accessToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJrdnNzand0IiwiaWF0IjoxNTk2MDgwMTM3LCJleHAiOjE1OTg2NzIxMzcsImNsaWVudF9SZXRhaWxlcklkIjo3MzcyODAsImNsaWVudF9SZXRhaWxlckNvZGUiOiJ0ZXN0YXV0b215a2lvdCIsImNsaWVudF9Vc2VySWQiOjE2Nzk5LCJhdWQiOiJLaW90VmlldC5BcGkuSW50ZXJuYWwifQ.ET4kxABT3i8FJHG1MGUoEcmZh-eXnanrP7evNAE5laKxvkfBf4Do5V451VrsXII8oKU6K71LGvHROMFKNMTDxs51Ufr9jkr5qZnDMF5VY722CTllzPh4iRbDmUYrVQfq_XPDWQzPlJt1r1-eTm0kDjAVtRAk6vhaLR8jjAr7lLtG6le5kYrk7vT-YRkTncJj569jy74rBcc5kuW_X5wh_1Vly8hZHTbNXEqrB0vAKLBBLIrMawAm6Adms_CYEgPwp73I0T-1jbRp2S11WZjb_Zpc_M6WypcFSGCb32aSlEX7qJ149gx4U7VMJs9sTGb4FmZFxBMwWGbhIdoOO8VfQA","secertKey":"1f36fe67-a0f2-453b-bea5-9d778218279c","clientId":"5F16AD6044795B917F2F9E640F572EF835B71254","storeId":737280,"expiredAt":1598671939},"current_viewed_version":2.1,"keyCacheCategory":"7372801596685554-category-cache","lastModifiedFrom":"2020-08-05T11:24"}    #update config to default
